### ISSUE TITLE
Look into 3rd party booking tool

### ISSUE THREAD

**Issue by chriswhawkins** [b2io/the-elm-inn-website#18]
Look at options for service solutions to allow for booking of Dar's rooms on her website. Preferable to find a service that provides a copy/paste tool for use on website (with styling options) and an easy way to manage listings on other sites, too.

**Comment by zeroverride** [comment]
Investigating tools to handle online room reservations: 

BookingBug: Would need tailored to the industry but advertises that it has the styling tools that designers need to integrate it. Pricing starts at 19.95 per month but the solution that Dar would actually need (5 employees access) is 34.95 per month. https://www.bookingbug.com/hire-and-rental Doesn't look like it integrates off the shelf into other booking systems.

Lodgify: http://www.lodgify.com/ has the option to integrate it's booking system into your website (that being said the default template look pretty decent and affordable) I don't know if the pricing for integrating the booking engine into an existing website is different than the package price but the package price runs $20 - $40 I'm guessing that you have to use them as a Merchant account provider but the rates are probably comparable to anyone else. 

Gracesoft: http://www.gracesoft.com/easy-innkeeping/reservation-software.htm - Looks gross

Innquest: http://www.innquest.com/pricing/rm.php - $1000.00 one time fee. No, it's an on premise solution.

Rezovation: http://www.rezovation.com/pricing-web.html - Roughly $120.00 per month. Software is built by Homeaway that means it integrates into the Global booking system (which has a per reservation charge). Compelling option because it has the option for Card readers and other on premise solutions. Seems end to end. Touts it's "easy integration"  http://www.rezovation.com/rezovationgt/WebsiteIntegrationOptions.html - The rezovation website itself is less pretty than some of the others. 

Resnexus: https://resnexus.com/Pricing - Roughly $143.0 per month. Integrates into Tripadvisor as an option. Seems to have more marketing functions built in like direct email, anniversaries etc. has a big focus on building "packages" https://resnexus.com/Demo/BedAndBreakfastSoftware I don't see a whole lot of information on Integration. They offer a "turn key" business website as well

**Comment by chriswhawkins** [comment]
I reviewed these options, but lean more towards littlehotelier.com or freetobook.com
For now, will get started with a simple form.
